---
- op: replace
  path: /spec/template/spec/source/repoURL
  value: https://github.com/pmacik-testing/infra-deployments.git
- op: replace
  path: /spec/template/spec/source/targetRevision
  value: preview-main-elji
